[package]
name = "serverless-lando"
version = "0.1.0"
publish = false

[lib]
crate-type = ["cdylib"]
name = "lambda"

[dependencies]
envy = "0.3"
lando = "0.1"
cpython = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "*"
reqwest = "0.8"